--- 
document: 
  description: "L’Anagrafe Nazionale della Popolazione Residente (ANPR) è la banca dati nazionale nella quale confluiranno progressivamente le anagrafi comunali."
  name: "Documentazione tecnica"
  tags: 
    - anpr
